name = "lexi-nightfall"
license = "MIT"
licenselink = "https://github.com/alexiarstein/lexi-nightfall//blob/master/LICENSE"
description = "Minimal dark theme for Hugo, fork from Nightfall Theme"
homepage = "https://github.com/alexiarstein/lexi-nightfall/"
tags = ["minimal", "dark", "blog", "sass", "multilingual"]
features = ["blog", "sass", "dark", "multilingual"]
min_version = "0.80.0"

[author]
name = "Alexia Steinberg"
homepage = "https://lachicadesistemas.com.ar"
